### ISSUE TITLE
Manual drive straight method

### ISSUE THREAD

**Issue by ChuweyBar** [NRG948/NRGRobot2017#14] opened 2017-01-17 00:23 UTC
Now after we are using the Joysticks we can drive the robot, but pushing both of the joysticks at the same level does not mean that the robot will drive in a straight line. That's when the manual drive straight method saves the day, the driver can just hold a button and push one single joystick and the robot will drive perfectly straight. And it is your holy task to add this method.
Chuwei Guo
P.S. you can look back to last year's code and the rookie robot's code for references.

**Comment by gregoryquick** [comment] 2017-01-18 02:32
Need #23 before this can be done

**Comment by edreed** [comment] 2017-01-25 03:32
Duplicate of issue #25 which has been fixed.

**Closed as completed by edreed** 2017-01-25 03:32 UTC
Labels: Medium (Experienced Rookies/Veterans)
